### PR TITLE
Add replace command

### LINKED ISSUE #59: Feature request: sed
First off, nice tool! I was specifically looking for an easy way to search a Vault and grep fits the bill nicely. It would be nice to have a way to change strings recursively in Vault as well ala an in-place "`sed`". Flags could be used to apply only for keys, values or both. It'd make configuration changes very easy across multiple paths (which in our usage maps to different services).

Supporting regex on it (and grep for that matter) would be a big bonus.

### PR DESCRIPTION
**Pull request by fishi0x01**
Fixes #59

### CODE REVIEW

**Comment by mattlqx** [comment]
@fishi0x01 would you like me to take a stab at `replace` or do you want to continue on with this one? I think we could leverage some of grep's implementation for it at this point.

**Comment by fishi0x01** [comment]
@mattlqx Feel free to take this one over. Thanks a bunch again :bow: 

I will in the meanwhile work on this issue: https://github.com/fishi0x01/vsh/issues/67

**Comment by fishi0x01** [comment]
@mattlqx Id like to merge this [PR](https://github.com/fishi0x01/vsh/pull/68) now. It prevents fiddling with the metadata in KV2. However, it might affect your current work - so I could also wait with merging if you want.

**Comment by mattlqx** [comment]
Thanks for the consideration! That pull is a good improvement. Please go ahead and merge it.

**Comment by fishi0x01** [comment]
Implemented by #69

**Pull request closed without merging**
