### PR TITLE
build arm architectures

### PR DESCRIPTION
**Pull request by mattlqx**
I'm running on a MacBook Pro M1 so I would like native builds and tests
to use that native build.

### CODE REVIEW

**Comment by mattlqx** [comment]
After some testing, it appears that arm64 fails to build on amd64 platforms with go 1.15. Looks like this will be fixed in go 1.16, so I guess the easiest thing to do is just wait on this as 1.16 currently has an rc out.

**Comment by fishi0x01** [comment]
Looks like today is the day :sunglasses: 

https://blog.golang.org/go1.16

**Comment by fishi0x01** [comment]
I took the freedom to incorporate your idea in a new PR https://github.com/fishi0x01/vsh/pull/83 - the source of this PR is deleted, so I couldn't test or submit to it.

**Comment by mattlqx** [comment]
Ah yeah, thanks I deleted my fork when I was invited to this repo.

**Pull request closed without merging**
